name: Post Submit
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

permissions:
  contents: write
  pull-requests: read

jobs:
  push_to_registry:
    name: Build and push unversioned images to quay.io/medik8s
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with: 
          go-version-file: 'go.mod' 
          cache-dependency-path: 'go.sum' 

      - name: Log in to Quay.io
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          registry: quay.io

      - name: Build and push CSV version v0.0.1 with latest images
        run: make bundle container-build container-push
